#!/usr/bin/env python3
"""
data/regen_tables_from_dump.py — regenerate the aggregate result tables
from the newest merged per-trip dump (offset_sweep_per_trip_retuned_*.csv,
falling back to offset_sweep_per_trip_*.csv).

Written after a bug in data/retune_theta_wide.py's first regeneration: its
dump parser left an `error: None` KEY on every loaded row, and the
aggregation filter tests key membership, so all dump-loaded rows were
dropped and the regenerated tables carried empty my_ekf/coulomb/ocv/
rbc_coupled cells (n_errors = n_trips). The per-trip dumps themselves were
always correct; this script re-aggregates them with the fixed parser.

One command: venv/bin/python data/regen_tables_from_dump.py
"""
from __future__ import annotations

import glob
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import data.retune_theta_wide as rtw
import data.run_offset_sweep as ros
from validation.metrics import aggregate_trips, footnote_lines

RESULTS_DIR = ROOT / "results"
HEADLINE = ros.HEADLINE_OFFSET
FLEET_ORDER = list(ros.FLEET_PREPS.keys())


def load_newest_dump():
    cands = [Path(p) for pat in ("offset_sweep_per_trip_retuned_*.csv",
                                 "offset_sweep_per_trip_*.csv")
             for p in glob.glob(str(RESULTS_DIR / pat))]
    if not cands:
        sys.exit("no per-trip dump found")
    import csv
    # newest by mtime across both patterns (a stale retuned dump must not
    # shadow a fresher plain sweep dump)
    path = str(max(set(cands), key=lambda p: p.stat().st_mtime))
    results: Dict[str, Dict] = {}
    with open(path) as f:
        for row in csv.DictReader(f):
            m: Dict = {}
            for k, v in row.items():
                if k in ("dataset", "method", "offset_pp", "seg_index"):
                    continue
                if v == "":
                    m[k] = None
                elif k in rtw._FLOATS:
                    m[k] = float(v)
                else:
                    m[k] = v
            if m.get("error"):
                m = {"error": m["error"], "vehicle_id": m.get("vehicle_id")}
            else:
                m.pop("error", None)
            fleet = row["dataset"]
            key = (row["method"], float(row["offset_pp"]) / 100.0)
            results.setdefault(fleet, {}).setdefault(key, {})[int(row["seg_index"])] = m
    for fleet in results:
        base = results[fleet].get(("ocv_lookup", HEADLINE))
        if base:
            for off in ros.OFFSETS:
                results[fleet][("ocv_lookup", off)] = base
    return results, path


def main() -> None:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=ROOT,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    results, dump_path = load_newest_dump()
    print(f"Loaded {dump_path}")

    # sanity guard: no fleet/method cell may aggregate to zero valid trips
    for fleet in FLEET_ORDER:
        for method in ros.ALL_METHODS:
            d = results[fleet].get((method, HEADLINE), {})
            ok = [t for t in d.values() if t is not None and "error" not in t]
            if d and not ok:
                sys.exit(f"ABORT: {fleet}/{method} aggregated to 0 valid trips")
            print(f"  {fleet:18s} {method:12s} n={len(ok)}")

    censor_t: Dict[str, Optional[float]] = {}
    for fleet in FLEET_ORDER:
        ek = [t for t in results[fleet][("my_ekf", HEADLINE)].values()
              if t is not None and "error" not in t
              and t.get("t_conv_strict_s") is not None]
        censor_t[fleet] = (float(np.median([t["t_conv_strict_s"] for t in ek]))
                           if ek else None)

    def _trips(fleet, method, off):
        d = results[fleet].get((method, off), {})
        return [d[i] for i in sorted(d)]

    metas = sorted(glob.glob(str(RESULTS_DIR / "retune_meta_*.json")))
    changed = (json.loads(Path(metas[-1]).read_text())["changed_fleets"]
               if metas else [])
    hdr = [f"# regenerated by data/regen_tables_from_dump.py {stamp} "
           f"(git {commit}) from {Path(dump_path).name}; wide-grid θ; "
           f"changed fleets vs narrow grid: {changed or 'none'}; "
           f"my_ekf/coulomb/ocv_lookup rows from the cross-checked sweep",
           "# ocv_lookup is init-independent: identical values replicated "
           "across offset rows by construction",
           "# censoring threshold per dataset = EKF median strict t_conv at +20pp"]

    rows = [ros.sweep_row(fleet, method, off, _trips(fleet, method, off),
                          censor_t_s=censor_t[fleet])
            for fleet in FLEET_ORDER
            for method in ("my_ekf", "rbc_dekf", "coulomb", "ocv_lookup")
            for off in ros.OFFSETS]
    ros._write_csv(RESULTS_DIR / "offset_sweep.csv", hdr, ros.SWEEP_COLS, rows)

    rows20 = [ros.sweep_row(fleet, method, HEADLINE,
                            _trips(fleet, method, HEADLINE),
                            censor_t_s=censor_t[fleet])
              for fleet in FLEET_ORDER for method in ros.ALL_METHODS]
    ros._write_csv(RESULTS_DIR / "baseline_comparison.csv", hdr,
                   ros.SWEEP_COLS, rows20)

    rows0 = [ros.sweep_row(fleet, method, 0.0, _trips(fleet, method, 0.0),
                           censor_t_s=censor_t[fleet])
             for fleet in FLEET_ORDER
             for method in ("my_ekf", "rbc_dekf", "coulomb", "ocv_lookup")]
    ros._write_csv(RESULTS_DIR / "nominal_accuracy.csv",
                   hdr + ["# NOMINAL protocol: correct initial SOC (offset 0), "
                          "P0_soc=(2pp)^2 floor — unlike every other table, "
                          "which uses the adversarial wrong-init protocol"],
                   ros.SWEEP_COLS, rows0)
    md = ["# Nominal accuracy (offset = 0, correct initialization)", "",
          f"Regenerated {stamp} (wide-grid θ). Median (IQR) primary, mean "
          f"secondary — all pp.", "",
          "| Dataset | Method | n | RMSE med (IQR) | RMSE mean | MAE med "
          "| Converged% | Recovered% | Diverged% |",
          "|---|---|---|---|---|---|---|---|---|"]
    for r in rows0:
        md.append(
            f"| {r['dataset']} | {r['method']} | {r['n_trips']} "
            f"| {ros._f(r['rmse_median'], 2)} ({ros._f(r['rmse_q25'], 2)}–"
            f"{ros._f(r['rmse_q75'], 2)}) | {ros._f(r['rmse_mean'], 2)} "
            f"| {ros._f(r['mae_median'], 2)} "
            f"| {ros._f((r['conv_rate_strict'] or 0) * 100, 1)} "
            f"| {ros._f((r['rate_recovered'] or 0) * 100, 1)} "
            f"| {ros._f((r['rate_diverged'] or 0) * 100, 1)} |")
    md += ["", "> Nominal protocol: correct initial SOC; all other project "
           "tables use the +20 pp (or swept) adversarial wrong-init protocol.",
           *footnote_lines("> ")]
    (RESULTS_DIR / "nominal_accuracy.md").write_text("\n".join(md) + "\n")
    print(f"Wrote {RESULTS_DIR / 'nominal_accuracy.md'}")

    ros._write_csv(
        RESULTS_DIR / "outcome_tiers.csv", hdr,
        ["dataset", "method", "n_trips", "conv_rate_strict", "conv_rate_hold",
         "conv_rate_legacy", "rate_converged", "rate_recovered",
         "rate_diverged", "n_censored", "conv_rate_strict_censaware",
         "censor_t_s"],
        [{**ros.sweep_row(fleet, method, HEADLINE,
                          _trips(fleet, method, HEADLINE),
                          censor_t_s=censor_t[fleet]),
          "rate_converged": aggregate_trips(
              [t for t in _trips(fleet, method, HEADLINE)
               if t is not None and "error" not in t])["rate_converged"],
          "censor_t_s": censor_t[fleet]}
         for fleet in FLEET_ORDER for method in ros.ALL_METHODS])
    print("DONE.")


if __name__ == "__main__":
    main()
