#!/usr/bin/env python3
"""
analysis/identifiability_pass.py — standalone bias-identifiability check
(the final stage of data/retune_theta_wide.py, re-run after a pickling bug:
the pool worker must live at module level).

For every held-out segment, runs rbc_dekf @ +20 pp with the FINAL wide-grid
(Q_θ, R_θ) from the latest results/theta_tuning_wide_*.json and records the
final bias θ_end, the SIGNED trip-end SOC error, and the segment-mean
|∂OCV/∂SOC| of the fleet-fitted OCV. Per dataset it reports the Pearson r
of θ_end against −slope·err_end — the "θ absorbs SOC error" signature —
plus the ingredients for the Q_θ-vs-slope correlation across datasets.

Output: results/identifiability_check.csv
One command: venv/bin/python -u analysis/identifiability_pass.py
"""
from __future__ import annotations

import csv
import glob
import json
import multiprocessing as mp
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import data.run_offset_sweep as ros

RESULTS_DIR = ROOT / "results"
HEADLINE = ros.HEADLINE_OFFSET
N_WORKERS = max(1, (os.cpu_count() or 4) - 2)
CTX = mp.get_context("fork")


def _ident_worker(task):
    fleet, idx = task
    fl = ros._FLEETS[fleet]
    seg_df, vid, cfg = fl["eval"][idx]
    try:
        filt = ros._make_filter("rbc_dekf", cfg, fl["cal"], fl["ocv_fn"],
                                HEADLINE, fl["theta_qr"])
        t, est, tru, _ = ros.run_lean_traj(seg_df, cfg, filt, HEADLINE)
        h = 0.005
        ocv = fl["ocv_fn"] if fl["ocv_fn"] is not None else filt._ocv
        s = np.clip(tru, 0.01, 0.99)
        sub = s[:: max(1, len(s) // 200)]
        slopes = np.array([(float(ocv(x + h)) - float(ocv(x - h))) / (2 * h)
                           for x in sub])
        return (fleet, idx, {
            "theta_end_mV": float(filt.theta) * 1000.0,
            "soc_err_end_signed_pp": float(est[-1] - tru[-1]) * 100.0,
            "slope_mean_V_per_soc": float(np.mean(np.abs(slopes))),
        })
    except Exception as exc:
        return (fleet, idx, {"error": str(exc)})


def main() -> None:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    tunes = sorted(glob.glob(str(RESULTS_DIR / "theta_tuning_wide_*.json")))
    if not tunes:
        sys.exit("no theta_tuning_wide_*.json found")
    tuning = json.loads(Path(tunes[-1]).read_text())

    for fleet, prep in ros.FLEET_PREPS.items():
        print(f"[{fleet}] loading + calibration…")
        eval_items, cal_items, cal = prep()
        ros._FLEETS[fleet] = {
            "eval": eval_items, "cal_items": cal_items, "cal": cal,
            "ocv_fn": (cal.ocv_fn if cal else None),
            "theta_qr": (tuning[fleet]["chosen_Q_theta_V2_per_s"],
                         tuning[fleet]["chosen_R_theta_V2"]),
        }

    tasks = [(fleet, i) for fleet in ros.FLEET_PREPS
             for i in range(len(ros._FLEETS[fleet]["eval"]))]
    print(f"{len(tasks)} identifiability evaluations on {N_WORKERS} workers…")
    ident: Dict[str, List[Dict]] = {fleet: [] for fleet in ros.FLEET_PREPS}
    with CTX.Pool(N_WORKERS) as pool:
        for fleet, idx, m in pool.imap_unordered(_ident_worker, tasks,
                                                 chunksize=16):
            ident[fleet].append(m)

    rows = []
    for fleet in ros.FLEET_PREPS:
        ok = [m for m in ident[fleet] if "error" not in m]
        th = np.array([m["theta_end_mV"] for m in ok])
        er = np.array([m["soc_err_end_signed_pp"] for m in ok])
        sl = np.array([m["slope_mean_V_per_soc"] for m in ok])
        pred = -sl * (er / 100.0) * 1000.0
        r = (float(np.corrcoef(th, pred)[0, 1])
             if len(ok) > 2 and np.std(th) > 1e-9 and np.std(pred) > 1e-9
             else None)
        rows.append({
            "dataset": fleet, "n": len(ok),
            "mean_abs_docv_dsoc_V": float(np.mean(sl)),
            "chosen_Q_theta_V2_per_s": ros._FLEETS[fleet]["theta_qr"][0],
            "chosen_R_theta_V2": ros._FLEETS[fleet]["theta_qr"][1],
            "median_abs_theta_end_mV": float(np.median(np.abs(th))),
            "corr_theta_vs_minus_slope_err": r,
            "median_signed_err_end_pp": float(np.median(er)),
        })
        print(rows[-1])

    path = RESULTS_DIR / "identifiability_check.csv"
    with path.open("w", newline="") as f:
        f.write(f"# generated by analysis/identifiability_pass.py {stamp}; "
                f"rbc_dekf @ +20pp with final wide-grid (Q_theta,R_theta); "
                f"corr column = Pearson r of theta_end vs -slope*err_end "
                f"(the 'theta absorbs SOC error' signature); corr empty when "
                f"theta is degenerate (bias filter tuned OFF)\n")
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        for r_ in rows:
            w.writerow({k: ("" if v is None else v) for k, v in r_.items()})
    print(f"Wrote {path}")


if __name__ == "__main__":
    main()
